export const CATEGORIES = {
  MARKER: {
    order: 0,
    name: 'Marker',
    patterns: [/^group$/, /^peer$/],
  },
  LAYOUT: {
    order: 1,
    name: 'Layout',
    patterns: [
      /^absolute$/,
      /^align-/,
      /^auto-(cols|rows)-/,
      /^block$/,
      /^col-/,
      /^columns-/,
      /^container$/,
      /^content-/,
      /^contents$/,
      /^fixed$/,
      /^flex$/,
      /^flex-(row|col|wrap|nowrap|flow)/,
      /^flow-root$/,
      /^gap-/,
      /^grid$/,
      /^grid-(cols|rows|flow)-/,
      /^hidden$/,
      /^inline$/,
      /^inline-(block|flex|grid|table)$/,
      /^items-/,
      /^justify-/,
      /^list-item$/,
      /^order-/,
      /^place-/,
      /^relative$/,
      /^row-/,
      /^self-/,
      /^static$/,
      /^sticky$/,
      /^table$/,
      /^table-(caption|cell|column|footer|header|row)/,
    ],
  },
  STRUCTURE: {
    order: 2,
    name: 'Structure',
    patterns: [
      /^aspect-/,
      /^basis-/,
      /^border(?:-[trblxyse])?(?:-(?:\d+|\[[^\]]+]))?$/,
      /^border-(collapse|separate)$/,
      /^border-spacing-/,
      /^bottom-/,
      /^box-(border|content)$/,
      /^clear-/,
      /^collapse$/,
      /^flex-(1|auto|initial|none|grow|shrink)/,
      /^float-/,
      /^grow(?:-|$)/,
      /^h-/,
      /^inset-/,
      /^invisible$/,
      /^left-/,
      /^-?m[xytrbl]?-/,
      /^max-h-/,
      /^max-w-/,
      /^min-h-/,
      /^min-w-/,
      /^object-/,
      /^overflow-/,
      /^overscroll-/,
      /^p[xytrbl]?-/,
      /^right-/,
      /^rounded(?:-|$)/,
      /^shrink(?:-|$)/,
      /^size-/,
      /^space-[xy]-/,
      /^top-/,
      /^visible$/,
      /^w-/,
      /^z-/,
    ],
  },
  STYLE: {
    order: 3,
    name: 'Style',
    patterns: [
      /^accent-/,
      /^appearance-/,
      /^backdrop-/,
      /^bg-(?!blend)/,
      /^bg-blend-/,
      /^blur/,
      /^border-(?:solid|dashed|dotted|double|hidden|none|collapse|separate)$/,
      /^border-(?:spacing|opacity)-/,
      /^border-[a-z]/,
      /^break-/,
      /^brightness-/,
      /^caret-/,
      /^content-/,
      /^contrast-/,
      /^cursor-/,
      /^decoration-/,
      /^divide-/,
      /^drop-shadow/,
      /^fill-/,
      /^filter$/,
      /^font-/,
      /^from-/,
      /^gradient-/,
      /^grayscale/,
      /^hue-rotate-/,
      /^indent-/,
      /^invert/,
      /^isolate$/,
      /^isolation-/,
      /^leading-/,
      /^line-clamp-/,
      /^line-through$/,
      /^list-/,
      /^mix-blend-/,
      /^no-underline$/,
      /^opacity-/,
      /^outline-/,
      /^overline$/,
      /^placeholder-/,
      /^pointer-events-/,
      /^resize/,
      /^ring-/,
      /^saturate-/,
      /^scroll-/,
      /^select-/,
      /^sepia(?:-|$)/,
      /^shadow-/,
      /^snap-/,
      /^stroke-/,
      /^text-/,
      /^to-/,
      /^touch-/,
      /^tracking-/,
      /^truncate$/,
      /^typography-/,
      /^underline$/,
      /^via-/,
      /^whitespace-/,
      /^will-change-/,
    ],
  },
  TRANSITION: {
    order: 4,
    name: 'Transition',
    patterns: [
      /^animate-/,
      /^delay-/,
      /^duration-/,
      /^ease-/,
      /^origin-/,
      /^-?rotate-/,
      /^scale-/,
      /^-?skew-/,
      /^transform/,
      /^transition/,
      /^-?translate-/,
    ],
  },
  INTERACTION: {
    order: 5,
    name: 'Interaction',
    patterns: [/^focus(?:-(?:within|visible))?:/, /^hover:/],
  },
  STATE: {
    order: 6,
    name: 'State',
    patterns: [
      /^active:/,
      /^autofill:/,
      /^checked:/,
      /^default:/,
      /^disabled:/,
      /^empty:/,
      /^enabled:/,
      /^even:/,
      /^first(?:-of-type)?:/,
      /^group-(?:aria-selected|active|checked|disabled|focus|hover):/,
      /^in-range:/,
      /^indeterminate:/,
      /^invalid:/,
      /^last(?:-of-type)?:/,
      /^odd:/,
      /^only:/,
      /^open:/,
      /^out-of-range:/,
      /^peer-(?:aria-selected|active|checked|disabled|focus|hover):/,
      /^placeholder(?:-shown)?:/,
      /^read-only:/,
      /^required:/,
      /^target:/,
      /^valid:/,
      /^visited:/,
    ],
  },
  ACCESSIBILITY: {
    order: 7,
    name: 'Accessibility',
    patterns: [/^aria-/, /^(?:not-)?sr-only$/],
  },
  CVA: {
    order: 8,
    name: 'Custom Variant',
    patterns: [],
  },
  CUSTOM: {
    order: 9,
    name: 'Custom',
    patterns: [],
  },
} as const;

const categories = Object.values(CATEGORIES).filter((category) => category.patterns.length > 0);

export function getCategoryOrder(className: string): number {
  const firstClass = className.trim().split(/\s+/)[0];

  if (!firstClass) {
    return CATEGORIES.CUSTOM.order;
  }

  const targetClass = firstClass.replace(/^(?:(?:sm|md|lg|xl|2xl|dark):|\[[^\]]+]:)+/, '');

  for (const category of categories) {
    if (category.patterns.some((pattern) => pattern.test(targetClass))) {
      return category.order;
    }
  }

  return CATEGORIES.CUSTOM.order;
}

export function getCategoryName(order: number): string {
  return categories.find((c) => c.order === order)?.name ?? CATEGORIES.CUSTOM.name;
}
